name: Healthcheck ping

on:
  push:
    branches:
      - master

jobs:
  healthcheck-ping:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedex-26uo.onrender.com|https://pokedex-26uo.onrender.com/health